# Rutas absolutas de los directorios de medios
ruta.vid.pro1=C:\\DataBase\\img y vid\\vid\\Pro1
ruta.vid.pro2=C:\\DataBase\\img y vid\\vid\\Pro2
ruta.img.pro1=C:\\DataBase\\img y vid\\img\\Pro1
ruta.img.pro2=C:\\DataBase\\img y vid\\img\\Pro2

# Nombres de los pipes IPC de mpv
mpv.pipe.pro1=mpv_pro1
mpv.pipe.pro2=mpv_pro2
